# Generated by Django 4.2.7 on 2025-11-02 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="房間名稱")),
                (
                    "standard_line_score",
                    models.IntegerField(default=12, verbose_name="每一條線的總分 (L)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "房間",
                "verbose_name_plural": "房間",
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="路線名稱")),
                (
                    "grade",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="難度等級"
                    ),
                ),
                ("photo_url", models.URLField(blank=True, verbose_name="照片網址")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="scoring.room",
                        verbose_name="房間",
                    ),
                ),
            ],
            options={
                "verbose_name": "路線",
                "verbose_name_plural": "路線",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="成員名稱")),
                (
                    "is_custom_calc",
                    models.BooleanField(default=False, verbose_name="是否為客製化組"),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="總分",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="scoring.room",
                        verbose_name="房間",
                    ),
                ),
            ],
            options={
                "verbose_name": "成員",
                "verbose_name_plural": "成員",
                "ordering": ["-total_score", "name"],
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="是否完成"),
                ),
                (
                    "score_attained",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="獲得的分數",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="scoring.member",
                        verbose_name="成員",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="scoring.route",
                        verbose_name="路線",
                    ),
                ),
            ],
            options={
                "verbose_name": "成績",
                "verbose_name_plural": "成績",
                "ordering": ["-created_at"],
                "unique_together": {("member", "route")},
            },
        ),
    ]
