# Generated by Django 4.2.7 on 2025-11-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="route_photos/", verbose_name="照片"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="standard_line_score",
            field=models.IntegerField(default=1, verbose_name="每一條路線總分 (L)"),
        ),
        migrations.AlterField(
            model_name="route",
            name="photo_url",
            field=models.URLField(blank=True, verbose_name="照片網址（舊版，已棄用）"),
        ),
    ]
