# Generated by Django 4.2.7 on 2025-11-06 23:23

from django.db import migrations, models
import scoring.models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0002_route_photo_alter_room_standard_line_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=scoring.models.route_photo_upload_path,
                verbose_name="照片",
            ),
        ),
    ]
